//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4216
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4216.
// 
#pragma warning disable 1591

namespace ChecksumValidation.ChecksumClient.ChecksumValidationSoapServer {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChecksumValidationSoap", Namespace="http://www.ethical-hacking.de/ChecksumValidation/")]
    public partial class ChecksumValidation : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SecuritySettings securitySettingsValueField;
        
        private System.Threading.SendOrPostCallback LoadBankDirectoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateBankAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormatBlzOperationCompleted;
        
        private System.Threading.SendOrPostCallback ToIbanOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateIbanOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormatIbanOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateCreditCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCreditCardTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateGermanIdentityCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateGermanPassportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChecksumValidation() {
            this.Url = global::ChecksumValidation.ChecksumClient.Properties.Settings.Default.ChecksumClient_ChecksumValidationSoapServer_ChecksumValidation;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SecuritySettings SecuritySettingsValue {
            get {
                return this.securitySettingsValueField;
            }
            set {
                this.securitySettingsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoadBankDirectoryCompletedEventHandler LoadBankDirectoryCompleted;
        
        /// <remarks/>
        public event ValidateBankAccountCompletedEventHandler ValidateBankAccountCompleted;
        
        /// <remarks/>
        public event FormatBlzCompletedEventHandler FormatBlzCompleted;
        
        /// <remarks/>
        public event ToIbanCompletedEventHandler ToIbanCompleted;
        
        /// <remarks/>
        public event ValidateIbanCompletedEventHandler ValidateIbanCompleted;
        
        /// <remarks/>
        public event FormatIbanCompletedEventHandler FormatIbanCompleted;
        
        /// <remarks/>
        public event ValidateCreditCardCompletedEventHandler ValidateCreditCardCompleted;
        
        /// <remarks/>
        public event GetCreditCardTypeCompletedEventHandler GetCreditCardTypeCompleted;
        
        /// <remarks/>
        public event ValidateGermanIdentityCardCompletedEventHandler ValidateGermanIdentityCardCompleted;
        
        /// <remarks/>
        public event ValidateGermanPassportCompletedEventHandler ValidateGermanPassportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuritySettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ethical-hacking.de/ChecksumValidation/LoadBankDirectory", RequestNamespace="http://www.ethical-hacking.de/ChecksumValidation/", ResponseNamespace="http://www.ethical-hacking.de/ChecksumValidation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoadBankDirectory() {
            object[] results = this.Invoke("LoadBankDirectory", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadBankDirectoryAsync() {
            this.LoadBankDirectoryAsync(null);
        }
        
        /// <remarks/>
        public void LoadBankDirectoryAsync(object userState) {
            if ((this.LoadBankDirectoryOperationCompleted == null)) {
                this.LoadBankDirectoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadBankDirectoryOperationCompleted);
            }
            this.InvokeAsync("LoadBankDirectory", new object[0], this.LoadBankDirectoryOperationCompleted, userState);
        }
        
        private void OnLoadBankDirectoryOperationCompleted(object arg) {
            if ((this.LoadBankDirectoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadBankDirectoryCompleted(this, new LoadBankDirectoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuritySettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ethical-hacking.de/ChecksumValidation/ValidateBankAccount", RequestNamespace="http://www.ethical-hacking.de/ChecksumValidation/", ResponseNamespace="http://www.ethical-hacking.de/ChecksumValidation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateBankAccount(string blz, string account) {
            object[] results = this.Invoke("ValidateBankAccount", new object[] {
                        blz,
                        account});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateBankAccountAsync(string blz, string account) {
            this.ValidateBankAccountAsync(blz, account, null);
        }
        
        /// <remarks/>
        public void ValidateBankAccountAsync(string blz, string account, object userState) {
            if ((this.ValidateBankAccountOperationCompleted == null)) {
                this.ValidateBankAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateBankAccountOperationCompleted);
            }
            this.InvokeAsync("ValidateBankAccount", new object[] {
                        blz,
                        account}, this.ValidateBankAccountOperationCompleted, userState);
        }
        
        private void OnValidateBankAccountOperationCompleted(object arg) {
            if ((this.ValidateBankAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateBankAccountCompleted(this, new ValidateBankAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuritySettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ethical-hacking.de/ChecksumValidation/FormatBlz", RequestNamespace="http://www.ethical-hacking.de/ChecksumValidation/", ResponseNamespace="http://www.ethical-hacking.de/ChecksumValidation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FormatBlz(string blz) {
            object[] results = this.Invoke("FormatBlz", new object[] {
                        blz});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormatBlzAsync(string blz) {
            this.FormatBlzAsync(blz, null);
        }
        
        /// <remarks/>
        public void FormatBlzAsync(string blz, object userState) {
            if ((this.FormatBlzOperationCompleted == null)) {
                this.FormatBlzOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormatBlzOperationCompleted);
            }
            this.InvokeAsync("FormatBlz", new object[] {
                        blz}, this.FormatBlzOperationCompleted, userState);
        }
        
        private void OnFormatBlzOperationCompleted(object arg) {
            if ((this.FormatBlzCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormatBlzCompleted(this, new FormatBlzCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuritySettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ethical-hacking.de/ChecksumValidation/ToIban", RequestNamespace="http://www.ethical-hacking.de/ChecksumValidation/", ResponseNamespace="http://www.ethical-hacking.de/ChecksumValidation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ToIban(string blz, string account) {
            object[] results = this.Invoke("ToIban", new object[] {
                        blz,
                        account});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ToIbanAsync(string blz, string account) {
            this.ToIbanAsync(blz, account, null);
        }
        
        /// <remarks/>
        public void ToIbanAsync(string blz, string account, object userState) {
            if ((this.ToIbanOperationCompleted == null)) {
                this.ToIbanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnToIbanOperationCompleted);
            }
            this.InvokeAsync("ToIban", new object[] {
                        blz,
                        account}, this.ToIbanOperationCompleted, userState);
        }
        
        private void OnToIbanOperationCompleted(object arg) {
            if ((this.ToIbanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ToIbanCompleted(this, new ToIbanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuritySettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ethical-hacking.de/ChecksumValidation/ValidateIban", RequestNamespace="http://www.ethical-hacking.de/ChecksumValidation/", ResponseNamespace="http://www.ethical-hacking.de/ChecksumValidation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateIban(string iban) {
            object[] results = this.Invoke("ValidateIban", new object[] {
                        iban});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateIbanAsync(string iban) {
            this.ValidateIbanAsync(iban, null);
        }
        
        /// <remarks/>
        public void ValidateIbanAsync(string iban, object userState) {
            if ((this.ValidateIbanOperationCompleted == null)) {
                this.ValidateIbanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateIbanOperationCompleted);
            }
            this.InvokeAsync("ValidateIban", new object[] {
                        iban}, this.ValidateIbanOperationCompleted, userState);
        }
        
        private void OnValidateIbanOperationCompleted(object arg) {
            if ((this.ValidateIbanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateIbanCompleted(this, new ValidateIbanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuritySettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ethical-hacking.de/ChecksumValidation/FormatIban", RequestNamespace="http://www.ethical-hacking.de/ChecksumValidation/", ResponseNamespace="http://www.ethical-hacking.de/ChecksumValidation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FormatIban(string iban) {
            object[] results = this.Invoke("FormatIban", new object[] {
                        iban});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormatIbanAsync(string iban) {
            this.FormatIbanAsync(iban, null);
        }
        
        /// <remarks/>
        public void FormatIbanAsync(string iban, object userState) {
            if ((this.FormatIbanOperationCompleted == null)) {
                this.FormatIbanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormatIbanOperationCompleted);
            }
            this.InvokeAsync("FormatIban", new object[] {
                        iban}, this.FormatIbanOperationCompleted, userState);
        }
        
        private void OnFormatIbanOperationCompleted(object arg) {
            if ((this.FormatIbanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormatIbanCompleted(this, new FormatIbanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuritySettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ethical-hacking.de/ChecksumValidation/ValidateCreditCard", RequestNamespace="http://www.ethical-hacking.de/ChecksumValidation/", ResponseNamespace="http://www.ethical-hacking.de/ChecksumValidation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateCreditCard(string creditCardNumber) {
            object[] results = this.Invoke("ValidateCreditCard", new object[] {
                        creditCardNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateCreditCardAsync(string creditCardNumber) {
            this.ValidateCreditCardAsync(creditCardNumber, null);
        }
        
        /// <remarks/>
        public void ValidateCreditCardAsync(string creditCardNumber, object userState) {
            if ((this.ValidateCreditCardOperationCompleted == null)) {
                this.ValidateCreditCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateCreditCardOperationCompleted);
            }
            this.InvokeAsync("ValidateCreditCard", new object[] {
                        creditCardNumber}, this.ValidateCreditCardOperationCompleted, userState);
        }
        
        private void OnValidateCreditCardOperationCompleted(object arg) {
            if ((this.ValidateCreditCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateCreditCardCompleted(this, new ValidateCreditCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuritySettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ethical-hacking.de/ChecksumValidation/GetCreditCardType", RequestNamespace="http://www.ethical-hacking.de/ChecksumValidation/", ResponseNamespace="http://www.ethical-hacking.de/ChecksumValidation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCreditCardType(string creditCardNumber) {
            object[] results = this.Invoke("GetCreditCardType", new object[] {
                        creditCardNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCreditCardTypeAsync(string creditCardNumber) {
            this.GetCreditCardTypeAsync(creditCardNumber, null);
        }
        
        /// <remarks/>
        public void GetCreditCardTypeAsync(string creditCardNumber, object userState) {
            if ((this.GetCreditCardTypeOperationCompleted == null)) {
                this.GetCreditCardTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCreditCardTypeOperationCompleted);
            }
            this.InvokeAsync("GetCreditCardType", new object[] {
                        creditCardNumber}, this.GetCreditCardTypeOperationCompleted, userState);
        }
        
        private void OnGetCreditCardTypeOperationCompleted(object arg) {
            if ((this.GetCreditCardTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCreditCardTypeCompleted(this, new GetCreditCardTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuritySettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ethical-hacking.de/ChecksumValidation/ValidateGermanIdentityCard", RequestNamespace="http://www.ethical-hacking.de/ChecksumValidation/", ResponseNamespace="http://www.ethical-hacking.de/ChecksumValidation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateGermanIdentityCard(string identityId) {
            object[] results = this.Invoke("ValidateGermanIdentityCard", new object[] {
                        identityId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateGermanIdentityCardAsync(string identityId) {
            this.ValidateGermanIdentityCardAsync(identityId, null);
        }
        
        /// <remarks/>
        public void ValidateGermanIdentityCardAsync(string identityId, object userState) {
            if ((this.ValidateGermanIdentityCardOperationCompleted == null)) {
                this.ValidateGermanIdentityCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateGermanIdentityCardOperationCompleted);
            }
            this.InvokeAsync("ValidateGermanIdentityCard", new object[] {
                        identityId}, this.ValidateGermanIdentityCardOperationCompleted, userState);
        }
        
        private void OnValidateGermanIdentityCardOperationCompleted(object arg) {
            if ((this.ValidateGermanIdentityCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateGermanIdentityCardCompleted(this, new ValidateGermanIdentityCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecuritySettingsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ethical-hacking.de/ChecksumValidation/ValidateGermanPassport", RequestNamespace="http://www.ethical-hacking.de/ChecksumValidation/", ResponseNamespace="http://www.ethical-hacking.de/ChecksumValidation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateGermanPassport(string identityId) {
            object[] results = this.Invoke("ValidateGermanPassport", new object[] {
                        identityId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateGermanPassportAsync(string identityId) {
            this.ValidateGermanPassportAsync(identityId, null);
        }
        
        /// <remarks/>
        public void ValidateGermanPassportAsync(string identityId, object userState) {
            if ((this.ValidateGermanPassportOperationCompleted == null)) {
                this.ValidateGermanPassportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateGermanPassportOperationCompleted);
            }
            this.InvokeAsync("ValidateGermanPassport", new object[] {
                        identityId}, this.ValidateGermanPassportOperationCompleted, userState);
        }
        
        private void OnValidateGermanPassportOperationCompleted(object arg) {
            if ((this.ValidateGermanPassportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateGermanPassportCompleted(this, new ValidateGermanPassportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4016")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ethical-hacking.de/ChecksumValidation/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ethical-hacking.de/ChecksumValidation/", IsNullable=false)]
    public partial class SecuritySettings : System.Web.Services.Protocols.SoapHeader {
        
        private string secureConnectionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string secureConnection {
            get {
                return this.secureConnectionField;
            }
            set {
                this.secureConnectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void LoadBankDirectoryCompletedEventHandler(object sender, LoadBankDirectoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadBankDirectoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadBankDirectoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void ValidateBankAccountCompletedEventHandler(object sender, ValidateBankAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateBankAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateBankAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void FormatBlzCompletedEventHandler(object sender, FormatBlzCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormatBlzCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormatBlzCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void ToIbanCompletedEventHandler(object sender, ToIbanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ToIbanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ToIbanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void ValidateIbanCompletedEventHandler(object sender, ValidateIbanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateIbanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateIbanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void FormatIbanCompletedEventHandler(object sender, FormatIbanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormatIbanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormatIbanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void ValidateCreditCardCompletedEventHandler(object sender, ValidateCreditCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateCreditCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateCreditCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void GetCreditCardTypeCompletedEventHandler(object sender, GetCreditCardTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCreditCardTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCreditCardTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void ValidateGermanIdentityCardCompletedEventHandler(object sender, ValidateGermanIdentityCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateGermanIdentityCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateGermanIdentityCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    public delegate void ValidateGermanPassportCompletedEventHandler(object sender, ValidateGermanPassportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4016")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateGermanPassportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateGermanPassportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591